### ISSUE TITLE
dataset changed

### ISSUE THREAD

**Issue by yana-xuyan** [mrqa/MRQA-Shared-Task-2019#14]
Hi! I downloaded the dev sets twice, the first time is 7.6 and the second time is 7.16. But I found that the dev sets of HotpotQA are different in two downloads. May I ask, except the dev set of HotpotQA, is there any other modification on the datasets provided with the link?

**Comment by ajfisch** [comment]
The MD5 hashes are different because they are gzipped, but the contents should be the same. HotpotQA should also be largely the same set of questions and answers besides for a few examples, though the qid's were regenerated between versions.

If you look at the [README datasets section](https://github.com/mrqa/MRQA-Shared-Task-2019#datasets), it contains links to notes/issues explaining the changes.

**Comment by yana-xuyan** [comment]
Thank you for your reply!
