### ISSUE TITLE
Duplicate paragraph in HotpotQA training set

### ISSUE THREAD

**Issue by boyang-nlp** [mrqa/MRQA-Shared-Task-2019#7]
I noticed that some duplicate paragraphs exist in HotpotQA training set as shown in the following pictures, is it reasonable? Thanks! 
![image](https://user-images.githubusercontent.com/8281515/59325345-48663c00-8d15-11e9-81dd-e4a6a439829d.png)
![image](https://user-images.githubusercontent.com/8281515/59325350-4bf9c300-8d15-11e9-8a28-a1bc388e5f70.png)

**Comment by boyang-nlp** [comment]
@danqi @robinjia @alontalmor @ajfisch could you please help to look into this issue? thanks.

**Comment by ajfisch** [comment]
Hi @scissorsy! Could you give the qid for those examples? Thanks!

**Comment by boyang-nlp** [comment]
Hi, @ajfisch ! At first glance, there're many such cases, for example: 
<img width="1172" alt="0e7b7238c366b988112468f3c" src="https://user-images.githubusercontent.com/8281515/59438805-c36b4780-8e26-11e9-9ef9-cd3ecabfb89d.png">
<img width="1164" alt="934c257e8b7d75e2a897aa2d4" src="https://user-images.githubusercontent.com/8281515/59438814-c5cda180-8e26-11e9-801e-02ebeb9f3cce.png">
<img width="1177" alt="6590d749f69bef962410664de" src="https://user-images.githubusercontent.com/8281515/59438827-c9612880-8e26-11e9-977f-a1fa8853891d.png">
<img width="1179" alt="b801893bab83f760e3dcbc82a" src="https://user-images.githubusercontent.com/8281515/59438832-cbc38280-8e26-11e9-9500-5d138c08b061.png">

**Comment by alontalmor** [comment]
Found the bug and fixed it, HotpotQA data update soon to follow

**Comment by ajfisch** [comment]
Updated. Thanks for reporting!

**Comment by boyang-nlp** [comment]
Got it,thanks a lot!

**Comment by csarron** [comment]
Hi @ajfisch and @alontalmor, this doesn't seem fixed, I can still see the duplicated sentences in the dev split. Just manually check the first 10 examples, I found 3 of them still contain duplicates.

e.g., the first example (id=5a8c7595554299585d9e36b6)
 
![Screenshot 2019-09-11 21 05 09](https://user-images.githubusercontent.com/8440740/64745985-ee257480-d4d7-11e9-85aa-4acdab3b511d.png)
and the fourth example, (id=5a85ea095542994775f606a8):
![Screenshot 2019-09-11 21 07 27](https://user-images.githubusercontent.com/8440740/64746080-46f50d00-d4d8-11e9-9b44-99bb51b9bbea.png)

10th example, (id=5a7166395542994082a3e814)
![Screenshot 2019-09-11 21 10 17](https://user-images.githubusercontent.com/8440740/64746208-b3700c00-d4d8-11e9-88cd-53e82c09b7db.png)

the problem seems still exist, or it didn't get fully fixed.

Note: I downloaded the dev split fresh from https://s3.us-east-2.amazonaws.com/mrqa/release/v2/dev/HotpotQA.jsonl.gz.

Is it possible that the problem got fixed, but somehow the s3 cache was not purged?

**Comment by cemilcengiz** [comment]
> Hi @ajfisch and @alontalmor, this doesn't seem fixed, I can still see the duplicated sentences in the dev split. Just manually check the first 10 examples, I found 3 of them still contain duplicates.
> 
> e.g., the first example (id=5a8c7595554299585d9e36b6)
> 
> ![Screenshot 2019-09-11 21 05 09](https://user-images.githubusercontent.com/8440740/64745985-ee257480-d4d7-11e9-85aa-4acdab3b511d.png)
> and the fourth example, (id=5a85ea095542994775f606a8):
> ![Screenshot 2019-09-11 21 07 27](https://user-images.githubusercontent.com/8440740/64746080-46f50d00-d4d8-11e9-9b44-99bb51b9bbea.png)
> 
> 10th example, (id=5a7166395542994082a3e814)
> ![Screenshot 2019-09-11 21 10 17](https://user-images.githubusercontent.com/8440740/64746208-b3700c00-d4d8-11e9-88cd-53e82c09b7db.png)
> 
> the problem seems still exist, or it didn't get fully fixed.
> 
> Note: I downloaded the dev split fresh from https://s3.us-east-2.amazonaws.com/mrqa/release/v2/dev/HotpotQA.jsonl.gz.
> 
> Is it possible that the problem got fixed, but somehow the s3 cache was not purged?

This problem still exists in 2021.
